name: schism_viz
channels:
  - pyviz # conda-forge causing issues ? https://discourse.holoviz.org/t/blank-output-with-latest-holoviz-from-conda-forge/2276/5
  - conda-forge
  - cadwr-dms
dependencies:
  - python=3.8
  - ipykernel #=6.17.1
  - autopep8
  - metpy
  - schimpy
  - xarray
  - pandas
  - hvplot
  - cartopy
  - shapely
  - geopandas
  - geoviews
  - spatialpandas
  - bokeh
  - plotly
  - matplotlib
  - scikit-learn
  - lxml
  - html5lib
  - notebook # needed for dashboard panel
