name: schismviz
channels:
  - pyviz # conda-forge causing issues ? https://discourse.holoviz.org/t/blank-output-with-latest-holoviz-from-conda-forge/2276/5
  - conda-forge
  - cadwr-dms
dependencies:
  - python=3.8
  - ipykernel #=6.17.1
  - autopep8
  - metpy
  - schimpy
  - numpy=1.23.5 # Temporary pin: Hitting this bug https://github.com/numba/numba/issues/8615
  - xarray
  - pandas
  - hvplot
  - ipywidgets # pyvista requires trame which requires ipywidgets
  - trame
  - pyvista # 3D plots
  - cartopy
  - shapely
  - geopandas
  - geoviews
  - spatialpandas
  - bokeh
  - plotly
  - matplotlib
  - scikit-learn
  - lxml
  - html5lib
  - notebook # needed for dashboard panel
